### ISSUE TITLE
Z 인덱스

### ISSUE THREAD

**Issue by tae2yi** [Adsenser/FullStack_Bootcamp#1]
Z-인덱스 - 무엇일까 & 왜일까?
문서 흐름과 poisition 속성을 사용해서 HTML 요소의 기본 위치를 변경하는 방법에 대해 배웠습니다.

기본 요소 위치를 변경하면 한 요소가 다른 요소와 겹치고 제어하려는 위치에서 어떤 요소가 다른 요소 위에 배치되는지 알 수 있습니다.

이러한 경우 z-index가 필요하죠.

어떻게 작동하나요

CSS 속성인 z-index는 위치 지정 요소(즉, position 속성이 static 값과 다른 값으로 적용된 요소)의 z-order를 정의합니다. z-order는 z-축을 참조하므로 해당되는 경우 요소가 서로 위에 쌓이는 방식을 제어합니다.

HTML 요소의 기본값은 auto로 설정되며 이는 0에 해당하죠. z-index가 높은 위치에 있는 요소는 z-index 값이 낮은 요소 위에 배치됩니다.

코드 예제
HTML
```html


<body>
    <div id="first">Element 1</div>
    <div id="second">Element 2</div>
</body>
```
CSS
```css
div {
    width: 200px;
    height: 200px;
    text-align: center;
    color: white;
}
 
#first {
    background-color: rgb(55, 117, 209);
}
 
#second {
    background-color: rgb(233, 137, 59);
}
```
기본적으로 두 요소 모두 문서 흐름을 따르며 요소 1이 먼저 표시되고 요소 2가 두 번째로 차례로 표시됩니다.

이제 #second에 다음 코드를 추가합니다.

    position: absolute;
    top: 0;
    left: 0;
요소 2는 문서 흐름에서 가져와서 요소 1 위에 표시됩니다.

z-index: 1을 #first에 추가해도 z-index는 기본 값인 position: static을 제외하고 배치된 요소에만 영향을 미치므로 z-축을 따라 요소의 순서가 변경되지 않습니다.

position: relative를 추가하면 #first를 기준으로 요소 1이 요소 2 위에 다시 표시됩니다.
